name: Belt Test Build

on:
    push:
        branches:
        - main

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Run build
          shell: cmd
          run: ./ep19/build.cmd

        - name: Save Community Package
          uses: actions/upload-artifact@v4
          with:
            name: community
            path: ./ep19/BeltTest/CommunityPackage/bin/**

        - name: Save Enterprise Package
          uses: actions/upload-artifact@v4
          with:
            name: enterprise
            path: ./ep19/BeltTest/EnterprisePackage/bin/**